---
title: "User Guide"
date: "April 10, 2025"
author: "Vet Scientia Team"
format: 
   html:
     embed-resources: true
     code-tools: true
     toc: true
     toc-depth: 3
     number-sections: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

## Introduction

The following document is a guide for students, teachers and admins alike to guide users on how to create an account, login, and use the features of our vet simulator

##  Account Management

### Sign-up

1. Navigate to the [sign-up page](https://gray-bush-0c1bf981e.6.azurestaticapps.net/signup) of our application
2. Enter in your credentials:
    1. First Name (Real name)
    2. Last Name (Real name)
    
    3. Email (Must use university/clinic email if domain checking is turned on for your organization)
    4.

### Login

## Super Admin

## University Admin

## Using the Simulator
Test out using the simulation with [Vet Scientia Demo](https://vs-capstone.itch.io/vs-demo).

To focus on the animal, click the animal.

To check the animal's vitals, focus on the animal and then hover over the animal. You will see a popup of the vitals like heart rate and respiratory rate.

To exit focus on any object, click the back button located towards the bottom of the screen.

To examine the drugs, click the cabinet on the left.

To look at the name of the a drug, hover over the drug.

To equip a drug, click the drug bottle.

To get a short description of the drug, click the thumbnail of the drug.

To apply a drug to the animal, equip the drug, focus on the animal, and then click the animal. The drug thumbnail should disappear.